import { useEffect,useState } from "react";
import { Edit3,Eye,Plus,Send,Trash2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import Page from "../../components/Page";
import { AddButton } from "../../components/Page";
import { Empty,Loading,Modal,SearchBox,StatusBadge } from "../../components/Common";
import { Field,Select,TextArea,TextInput } from "../../components/Forms";
import { services } from "../../services";import { apiError } from "../../lib/api";import { useAppDispatch } from "../../hooks";import { showToast } from "../../features/ui/uiSlice";import type {Assignment,ClassRoom,Course,Subject} from "../../types";import {formatDate} from "../../lib/format";

const initial={title:"",description:"",classId:"",courseId:"",subjectId:"",deadline:"",maximumMarks:100,allowUpdateBeforeDeadline:true,attachmentUrl:null as string|null};
export default function TeacherAssignments(){const dispatch=useAppDispatch();const nav=useNavigate();const[items,setItems]=useState<Assignment[]>([]);const[q,setQ]=useState("");const[status,setStatus]=useState("");const[modal,setModal]=useState(false);const[editing,setEditing]=useState<Assignment|null>(null);const[form,setForm]=useState<any>(initial);const[classes,setClasses]=useState<ClassRoom[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[subjects,setSubjects]=useState<Subject[]>([]);const[loading,setLoading]=useState(true);const[file,setFile]=useState<File|null>(null);const[uploading,setUploading]=useState(false);
const load=()=>{setLoading(true);services.assignments.mine({search:q,status:status||undefined,page:1,pageSize:100}).then(r=>setItems(r.items)).catch(e=>dispatch(showToast({type:"error",message:apiError(e)}))).finally(()=>setLoading(false))};useEffect(()=>{load();Promise.all([services.classes.list({pageSize:100}),services.courses.list({pageSize:100}),services.subjects.list({pageSize:100})]).then(([c,co,s])=>{setClasses(c.items);setCourses(co.items);setSubjects(s.items)}).catch(()=>{})},[]);useEffect(()=>{load()},[q,status]);
const open=(x?:Assignment)=>{setEditing(x??null);setFile(null);setForm(x?{...x,deadline:x.deadline.slice(0,16)}:{...initial,deadline:new Date(Date.now()+86400000).toISOString().slice(0,16)});setModal(true)};
const save=async(publish=false)=>{try{setUploading(true);let attachmentUrl=form.attachmentUrl??null;if(file) attachmentUrl=await services.upload("assignment",file);let a;if(editing)a=await services.assignments.update(editing.id,{...form,attachmentUrl,maximumMarks:Number(form.maximumMarks)});else a=await services.assignments.create({...form,attachmentUrl,maximumMarks:Number(form.maximumMarks)});if(publish)await services.assignments.publish(a.id);setModal(false);setFile(null);dispatch(showToast({type:"success",message:publish?"Assignment published.":"Draft saved."}));load()}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}finally{setUploading(false)}};
const remove=async(id:string)=>{if(!confirm("Delete this assignment?"))return;try{await services.assignments.remove(id);dispatch(showToast({type:"success",message:"Assignment deleted."}));load()}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}};
return <Page title="My assignments" subtitle="Create, publish and manage your academic work." action={<AddButton onClick={()=>open()}>Create assignment</AddButton>}><div className="toolbar"><SearchBox value={q} onChange={setQ}/><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Draft</option><option>Published</option><option>Closed</option></Select></div><div className="assignment-grid">{loading?<Loading/>:items.length===0?<Empty title="No assignments" text="Create your first assignment to get started."/>:items.map(a=><article className="assignment-card" key={a.id}><div className="assignment-top"><StatusBadge value={a.status}/><span>{formatDate(a.deadline)}</span></div><h3>{a.title}</h3><p>{a.description}</p><div className="assignment-meta"><span>Max marks <b>{a.maximumMarks}</b></span><span>Updates {a.allowUpdateBeforeDeadline?"allowed":"locked"}</span></div><div className="card-actions"><button className="btn btn-sm btn-secondary" onClick={()=>nav(`/teacher/assignments/${a.id}/submissions`)}><Eye size={15}/>Submissions</button>{a.status==="Draft"&&<button className="btn btn-sm btn-primary" onClick={()=>services.assignments.publish(a.id).then(()=>{dispatch(showToast({type:"success",message:"Published."}));load()}).catch(e=>dispatch(showToast({type:"error",message:apiError(e)})))}><Send size={15}/>Publish</button>}<button className="icon-btn" onClick={()=>open(a)}><Edit3 size={16}/></button><button className="icon-btn danger" onClick={()=>remove(a.id)}><Trash2 size={16}/></button></div></article>)}</div>
<Modal open={modal} onClose={()=>setModal(false)} title={editing?"Edit assignment":"Create assignment"} wide><div className="form-grid two"><Field label="Title"><TextInput value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Maximum marks"><TextInput type="number" min="1" value={form.maximumMarks} onChange={e=>setForm({...form,maximumMarks:e.target.value})}/></Field></div><Field label="Description"><TextArea rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="form-grid three"><Field label="Class"><Select value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,courseId:"",subjectId:""})}><option value="">Select</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Course"><Select value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value,subjectId:""})}><option value="">Select</option>{courses.filter(x=>x.classId===form.classId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Subject"><Select value={form.subjectId} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Select</option>{subjects.filter(x=>x.courseId===form.courseId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field></div><Field label="Deadline"><TextInput type="datetime-local" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></Field><Field label="Attachment (optional)"><input className="file-input" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp,.zip" onChange={e=>setFile(e.target.files?.[0]??null)}/>{form.attachmentUrl&&!file&&<a className="file-link" href={form.attachmentUrl} target="_blank" rel="noreferrer">Current attachment</a>}<small className="muted">PDF, Word, images or ZIP. Keep files within your backend upload limit.</small></Field><label className="check"><input type="checkbox" checked={form.allowUpdateBeforeDeadline} onChange={e=>setForm({...form,allowUpdateBeforeDeadline:e.target.checked})}/> Allow students to update before deadline</label><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn btn-secondary" onClick={()=>save(false)} disabled={uploading}>Save draft</button><button className="btn btn-primary" onClick={()=>save(true)} disabled={uploading}>{uploading ? "Uploading..." : editing ? "Save & publish" : "Create & publish"}</button></div></Modal></Page>}
