import { FormEvent,useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import Page from "../../components/Page";import {Loading,Modal,StatusBadge} from "../../components/Common";import {Field,TextArea} from "../../components/Forms";import {services} from "../../services";import {apiError} from "../../lib/api";import {useAppDispatch} from "../../hooks";import {showToast} from "../../features/ui/uiSlice";import type {Assignment,Submission} from "../../types";import {fileUrl,formatDateTime,isOverdue} from "../../lib/format";
export default function AssignmentDetail(){const{id}=useParams();const nav=useNavigate();const dispatch=useAppDispatch();const[a,setA]=useState<Assignment|null>(null);const[s,setS]=useState<Submission|null>(null);const[answer,setAnswer]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[confirm,setConfirm]=useState(false);const[file,setFile]=useState<File|null>(null);
const load=async()=>{if(!id)return;try{const[x,ss]=await Promise.all([services.assignments.get(id),services.submissions.mine()]);setA(x);const existing=ss.find(v=>v.assignmentId===id)??null;setS(existing);setAnswer(existing?.answer??"")}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}finally{setLoading(false)}};useEffect(()=>{load()},[id]);
const submit=async(e?:FormEvent)=>{e?.preventDefault();if(!a)return;if(!answer.trim())return dispatch(showToast({type:"error",message:"Please write your answer."}));setSaving(true);try{let attachmentUrl=s?.attachmentUrl??null;if(file) attachmentUrl=await services.upload("submission",file);const payload={assignmentId:a.id,answer,attachmentUrl};const x=s?await services.submissions.update(s.id,payload):await services.submissions.create(payload);setS(x);setFile(null);setConfirm(false);dispatch(showToast({type:"success",message:s?"Submission updated successfully.":"Assignment submitted successfully."}))}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}finally{setSaving(false)}};
if(loading)return <Page title="Assignment"><Loading/></Page>;if(!a)return <Page title="Assignment">Assignment not found.</Page>;
const canEdit=!isOverdue(a.deadline)&&a.allowUpdateBeforeDeadline&&s?.status!=="Graded";const canSubmit=!isOverdue(a.deadline)&&!s;
return <Page title={a.title} subtitle={`Deadline ${formatDateTime(a.deadline)} · ${a.maximumMarks} marks`}><div className="detail-grid"><article className="detail-card"><div className="detail-status"><StatusBadge value={s?.status??"Not submitted"}/><span>{isOverdue(a.deadline)?"Deadline passed":"Deadline active"}</span></div><h2>Assignment instructions</h2><div className="rich-text">{a.description}</div>{a.attachmentUrl&&<a className="file-link" href={fileUrl(a.attachmentUrl)} target="_blank" rel="noreferrer">Open assignment attachment</a>}<div className="deadline-box"><span>Deadline</span><b>{formatDateTime(a.deadline)}</b><small>Maximum marks: {a.maximumMarks}</small></div></article>
<article className="detail-card"><h2>{s?"Your submission":"Submit your answer"}</h2>{s&&<div className="submission-summary"><StatusBadge value={s.status}/>{s.marks!=null&&<strong>{s.marks} / {a.maximumMarks}</strong>}{s.feedback&&<p><b>Teacher feedback</b><br/>{s.feedback}</p>}</div>}<form onSubmit={submit}><Field label="Answer"><TextArea rows={14} value={answer} disabled={!canSubmit&&!canEdit} onChange={e=>setAnswer(e.target.value)} placeholder="Write your answer here..."/></Field>{(canSubmit||canEdit)&&<Field label="Attachment (optional)"><input className="file-input" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp,.zip" onChange={e=>setFile(e.target.files?.[0]??null)} />{s?.attachmentUrl&&!file&&<a className="file-link" href={fileUrl(s.attachmentUrl)} target="_blank" rel="noreferrer">Open submitted attachment</a>}<small className="muted">You can replace the attachment while updates are allowed.</small></Field>}{(canSubmit||canEdit)&&<button className="btn btn-primary btn-block" disabled={saving}>{saving?"Submitting...":s?"Update submission":"Submit assignment"}</button>}</form>{!canSubmit&&!canEdit&&<p className="muted">{s?.status==="Graded"?"This submission has been graded.":"The deadline has passed or editing is disabled."}</p>}</article></div><button className="btn btn-secondary" onClick={()=>nav("/student/assignments")}>Back to assignments</button><Modal open={confirm} onClose={()=>setConfirm(false)} title="Submit assignment"><p>Are you sure you want to submit? You can only edit it later if the assignment allows updates before the deadline.</p><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setConfirm(false)}>Review</button><button className="btn btn-primary" onClick={submit}>Confirm submission</button></div></Modal></Page>}
