import { useEffect, useState } from "react";
import Page,{AddButton} from "../../components/Page";
import { Empty, Loading, Modal } from "../../components/Common";
import { Field, Select } from "../../components/Forms";
import { services } from "../../services"; import { apiError } from "../../lib/api"; import { useAppDispatch } from "../../hooks"; import { showToast } from "../../features/ui/uiSlice"; import type {User,ClassRoom,Course,Subject,Enrollment,TeacherAssignment} from "../../types";

export function Enrollments(){const dispatch=useAppDispatch();const[items,setItems]=useState<Enrollment[]>([]);const[students,setStudents]=useState<User[]>([]);const[classes,setClasses]=useState<ClassRoom[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState({studentId:"",classId:"",courseId:""});const load=()=>services.enrollments.list().then(setItems).catch(e=>dispatch(showToast({type:"error",message:apiError(e)})));useEffect(()=>{load();Promise.all([services.users.list({role:"Student",pageSize:100}),services.classes.list({pageSize:100}),services.courses.list({pageSize:100})]).then(([s,c,co])=>{setStudents(s.items);setClasses(c.items);setCourses(co.items)}).catch(()=>{})},[]);
const save=async()=>{try{await services.enrollments.create(form);setOpen(false);setForm({studentId:"",classId:"",courseId:""});load();dispatch(showToast({type:"success",message:"Student enrolled."}))}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}};const remove=async(id:string)=>{if(confirm("Remove enrollment?")){await services.enrollments.remove(id);load()}};
return <Page title="Enrollments" subtitle="Connect students to their class and course." action={<AddButton onClick={()=>setOpen(true)}>Enroll student</AddButton>}><div className="table-card">{items.length===0?<Empty/>:<table><thead><tr><th>Student</th><th>Class</th><th>Course</th><th>Status</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{students.find(s=>s.id===x.studentId)?.firstName??x.studentId}</td><td>{classes.find(c=>c.id===x.classId)?.name??x.classId}</td><td>{courses.find(c=>c.id===x.courseId)?.name??x.courseId}</td><td>{x.isActive?"Active":"Inactive"}</td><td><button className="btn btn-sm btn-danger" onClick={()=>remove(x.id)}>Remove</button></td></tr>)}</tbody></table>}</div><Modal open={open} onClose={()=>setOpen(false)} title="Enroll student"><Field label="Student"><Select value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})}><option value="">Select student</option>{students.map(x=><option key={x.id} value={x.id}>{x.firstName} {x.lastName} — {x.email}</option>)}</Select></Field><Field label="Class"><Select value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,courseId:""})}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Course"><Select value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value})}><option value="">Select course</option>{courses.filter(x=>x.classId===form.classId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" onClick={save}>Enroll</button></div></Modal></Page>}

export function TeacherAssignments(){const dispatch=useAppDispatch();const[items,setItems]=useState<TeacherAssignment[]>([]);const[teachers,setTeachers]=useState<User[]>([]);const[classes,setClasses]=useState<ClassRoom[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[subjects,setSubjects]=useState<Subject[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState({teacherId:"",classId:"",courseId:"",subjectId:""});const load=()=>services.teacherAssignments.list().then(setItems).catch(e=>dispatch(showToast({type:"error",message:apiError(e)})));useEffect(()=>{load();Promise.all([services.users.list({role:"Teacher",pageSize:100}),services.classes.list({pageSize:100}),services.courses.list({pageSize:100}),services.subjects.list({pageSize:100})]).then(([t,c,co,s])=>{setTeachers(t.items);setClasses(c.items);setCourses(co.items);setSubjects(s.items)}).catch(()=>{})},[]);
const save=async()=>{try{await services.teacherAssignments.create(form);setOpen(false);load();dispatch(showToast({type:"success",message:"Teacher assigned."}))}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}};const remove=async(id:string)=>{if(confirm("Remove this assignment?")){await services.teacherAssignments.remove(id);load()}};
return <Page title="Teacher assignments" subtitle="Map teachers to the exact class, course and subject they can teach." action={<AddButton onClick={()=>setOpen(true)}>Assign teacher</AddButton>}><div className="table-card">{items.length===0?<Empty/>:<table><thead><tr><th>Teacher</th><th>Class</th><th>Course</th><th>Subject</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{teachers.find(t=>t.id===x.teacherId)?.firstName??x.teacherId}</td><td>{classes.find(c=>c.id===x.classId)?.name??x.classId}</td><td>{courses.find(c=>c.id===x.courseId)?.name??x.courseId}</td><td>{subjects.find(s=>s.id===x.subjectId)?.name??x.subjectId}</td><td><button className="btn btn-sm btn-danger" onClick={()=>remove(x.id)}>Remove</button></td></tr>)}</tbody></table>}</div><Modal open={open} onClose={()=>setOpen(false)} title="Assign teacher"><Field label="Teacher"><Select value={form.teacherId} onChange={e=>setForm({...form,teacherId:e.target.value})}><option value="">Select teacher</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.firstName} {x.lastName}</option>)}</Select></Field><Field label="Class"><Select value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,courseId:"",subjectId:""})}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Course"><Select value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value,subjectId:""})}><option value="">Select course</option>{courses.filter(x=>x.classId===form.classId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Subject"><Select value={form.subjectId} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Select subject</option>{subjects.filter(x=>x.courseId===form.courseId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" onClick={save}>Assign</button></div></Modal></Page>}
