import { useEffect, useState } from "react";
import { Edit3, Trash2 } from "lucide-react";
import Page,{AddButton} from "../../components/Page";
import { Empty, Loading, Modal, Pagination, SearchBox, StatusBadge } from "../../components/Common";
import { Field, Select, TextInput } from "../../components/Forms";
import { services } from "../../services"; import { apiError } from "../../lib/api"; import { useAppDispatch } from "../../hooks"; import { showToast } from "../../features/ui/uiSlice"; import type { User, Role } from "../../types";

const blank={firstName:"",lastName:"",email:"",phone:"",password:"",role:"Student" as Role,isActive:true};
export default function Users(){const dispatch=useAppDispatch();const[data,setData]=useState<{items:User[];total:number;page:number;pageSize:number}>({items:[],total:0,page:1,pageSize:20});const[q,setQ]=useState("");const[role,setRole]=useState("");const[modal,setModal]=useState(false);const[editing,setEditing]=useState<User|null>(null);const[form,setForm]=useState(blank);const[loading,setLoading]=useState(true);
const load=async(page=1)=>{setLoading(true);try{setData(await services.users.list({search:q,role:role||undefined,page,pageSize:20}));}catch(e){dispatch(showToast({type:"error",message:apiError(e)}));}finally{setLoading(false)}};useEffect(()=>{load(1)},[q,role]);
const open=(u?:User)=>{setEditing(u??null);setForm(u?{firstName:u.firstName,lastName:u.lastName,email:u.email,phone:u.phone,password:"",role:u.role,isActive:u.isActive}:blank);setModal(true)};
const save=async()=>{try{if(editing)await services.users.update(editing.id,form);else await services.users.create(form);setModal(false);dispatch(showToast({type:"success",message:"User saved successfully."}));load(data.page);}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}};
const remove=async(id:string)=>{if(!confirm("Delete this user?"))return;try{await services.users.remove(id);dispatch(showToast({type:"success",message:"User deleted."}));load(data.page)}catch(e){dispatch(showToast({type:"error",message:apiError(e)}))}};
return <Page title="Users" subtitle="Manage administrators, teachers and students." action={<AddButton onClick={()=>open()}>Create user</AddButton>}><div className="toolbar"><SearchBox value={q} onChange={setQ} placeholder="Search name, email or phone"/><Select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option>Admin</option><option>Teacher</option><option>Student</option></Select></div><div className="table-card">{loading?<Loading/>:data.items.length===0?<Empty/>:<table><thead><tr><th>User</th><th>Role</th><th>Phone</th><th>Status</th><th>Joined</th><th/></tr></thead><tbody>{data.items.map(u=><tr key={u.id}><td><div className="user-cell"><div className="avatar">{u.firstName[0]}{u.lastName[0]}</div><div><b>{u.firstName} {u.lastName}</b><small>{u.email}</small></div></div></td><td><StatusBadge value={u.role}/></td><td>{u.phone||"—"}</td><td><StatusBadge value={u.isActive?"Active":"Inactive"}/></td><td>{new Date(u.createdAt).toLocaleDateString()}</td><td><div className="row-actions"><button className="icon-btn" onClick={()=>open(u)}><Edit3 size={16}/></button><button className="icon-btn danger" onClick={()=>remove(u.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>}</div><Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={load}/>
<Modal open={modal} onClose={()=>setModal(false)} title={editing?"Edit user":"Create user"}><div className="form-grid two"><Field label="First name"><TextInput value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></Field><Field label="Last name"><TextInput value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></Field></div><Field label="Email"><TextInput type="email" disabled={!!editing} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Phone"><TextInput value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><div className="form-grid two"><Field label="Role"><Select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role})}><option>Admin</option><option>Teacher</option><option>Student</option></Select></Field>{!editing&&<Field label="Password"><TextInput type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field>}</div>{editing&&<label className="check"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active account</label>}<div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn btn-primary" onClick={save}>Save user</button></div></Modal></Page>}
